import type { Market } from "./markets";

export const fallbackMarkets: Market[] = [
  {
    id: "highest-grossing-movie-in-2026",
    title: "Highest grossing movie in 2026?",
    slug: "highest-grossing-movie-in-2026",
    description:
      "A live movie market tracking which film will finish 2026 as the highest global grosser.",
    category: "Movies",
    vertical: "Movies",
    tags: ["Movies", "Culture"],
    probability: 0.34,
    noProbability: 0.66,
    volume1mo: 4992453,
    volume24hr: 142290,
    volume1wk: 834402,
    liquidity: 1302276,
    endDate: "2026-12-31T00:00:00Z",
    updatedAt: "2026-06-08T00:00:00Z",
    source: "fallback",
  },
  {
    id: "polymarket-oscars-best-picture",
    title: "Polymarket Oscars Best Picture odds",
    slug: "polymarket-oscars-best-picture",
    description:
      "Oscar market hub for tracking market-implied Best Picture probabilities.",
    category: "Awards",
    vertical: "Awards",
    tags: ["Awards", "Oscars", "Movies"],
    probability: 0.22,
    noProbability: 0.78,
    volume1mo: 628,
    volume24hr: 19,
    volume1wk: 107,
    liquidity: 8653,
    endDate: "2027-02-28T00:00:00Z",
    updatedAt: "2026-06-08T00:00:00Z",
    source: "fallback",
  },
  {
    id: "next-james-bond-actor-odds",
    title: "Next James Bond actor?",
    slug: "next-james-bond-actor-odds",
    description:
      "Prediction market for who will be announced as the next James Bond actor.",
    category: "Movies",
    vertical: "Movies",
    tags: ["Movies", "Culture", "James Bond"],
    probability: 0.18,
    noProbability: 0.82,
    volume1mo: 858155,
    volume24hr: 17068,
    volume1wk: 46194,
    liquidity: 95085,
    endDate: "2026-06-30T00:00:00Z",
    updatedAt: "2026-06-08T00:00:00Z",
    source: "fallback",
  },
  {
    id: "love-island-odds",
    title: "Who will win Love Island USA Season 8?",
    slug: "love-island-odds",
    description:
      "Reality TV prediction-market page for Love Island winner odds and related markets.",
    category: "Reality TV",
    vertical: "Reality TV",
    tags: ["Reality TV", "Love Island", "Culture"],
    probability: 0.16,
    noProbability: 0.84,
    volume1mo: 244,
    volume24hr: 0,
    volume1wk: 244,
    liquidity: 4200,
    endDate: "2026-08-31T00:00:00Z",
    updatedAt: "2026-06-08T00:00:00Z",
    source: "fallback",
  },
  {
    id: "big-brother-odds",
    title: "Big Brother winner odds",
    slug: "big-brother-odds",
    description:
      "Reality TV odds page prepared for active Big Brother winner markets as they appear.",
    category: "Reality TV",
    vertical: "Reality TV",
    tags: ["Reality TV", "Big Brother", "Culture"],
    probability: 0.14,
    noProbability: 0.86,
    volume1mo: 140,
    volume24hr: 0,
    volume1wk: 0,
    liquidity: 1000,
    endDate: null,
    updatedAt: "2026-06-08T00:00:00Z",
    source: "fallback",
  },
  {
    id: "scary-movie-opening-weekend-box-office",
    title: '"Scary Movie" Opening Weekend Box Office',
    slug: "scary-movie-opening-weekend-box-office",
    description:
      "Opening weekend box office prediction market for the new Scary Movie release.",
    category: "Box Office",
    vertical: "Box Office",
    tags: ["Movies", "Box Office", "Culture"],
    probability: 0.62,
    noProbability: 0.38,
    volume1mo: 308870,
    volume24hr: 110809,
    volume1wk: 308870,
    liquidity: 87963,
    endDate: "2026-06-08T12:00:00Z",
    updatedAt: "2026-06-08T00:00:00Z",
    source: "fallback",
  },
];
